//! `cargo dev file-length`: no file of code may be longer than 500 lines (AGENTS.md, "Files of at
//! most 500 lines"). It lists the files of code git tracks that are longer, and fails when there
//! is one.

use std::process::Command;

use crate::{Fail, fail};

/// The most lines a file of code may have.
pub const MAX_LINES: usize = 500;

/// The extensions of files of code.
const CODE: &[&str] = &["rs", "ts", "js", "mjs", "cjs", "sh"];

/// Files that are code by their extension but not written by hand: recorded, vendored or
/// generated. A path is exempt when it starts with one of these (or, for the first, has it as a
/// directory anywhere).
const EXEMPT: &[(&str, &str)] = &[
    (
        "fixtures/",
        "test inputs, many of them third-party (anywhere in the tree)",
    ),
    ("testdata/", "recorded fixtures and third-party content"),
    (
        "crates/cms/assets/",
        "built from crates/cms/web by tools/cms/build.sh",
    ),
    ("crates/funcs/assets/katex/", "vendored KaTeX"),
    (
        "crates/highlight/src/chroma/lexers/",
        "converted from Chroma's XML (xml2rust)",
    ),
    (
        "crates/highlight/src/chroma/golexers/exported/",
        "converted from Chroma's XML (xml2rust)",
    ),
    (
        "crates/highlight/src/styles/",
        "converted from Chroma's XML (xml2rust)",
    ),
    (
        "crates/jsbuild/src/lower/es5/tests/table.rs",
        "generated by oracle/gen-table.cjs",
    ),
];

/// Whether `path` (relative to the repository) is a file of code the limit applies to.
pub fn is_checked(path: &str) -> bool {
    let is_code = path
        .rsplit_once('.')
        .is_some_and(|(_, extension)| CODE.contains(&extension));
    let (anywhere, prefix) = EXEMPT.split_at(1);
    let exempt = anywhere
        .iter()
        .any(|(dir, _)| path.starts_with(dir) || path.contains(&format!("/{dir}")))
        || prefix.iter().any(|(start, _)| path.starts_with(start));
    is_code && !exempt
}

/// The number of lines of `text`, a last line without a newline included.
pub fn line_count(text: &[u8]) -> usize {
    let newlines = text.iter().filter(|&&byte| byte == b'\n').count();
    newlines + usize::from(text.last().is_some_and(|&byte| byte != b'\n'))
}

pub fn run() -> Result<i32, Fail> {
    let root = crate::root();
    let listing = Command::new("git")
        .arg("-C")
        .arg(&root)
        .args(["ls-files", "-z"])
        .output()
        .map_err(|e| fail!("git ls-files: {e}"))?;
    if !listing.status.success() {
        return Err(fail!(
            "git ls-files: {}",
            String::from_utf8_lossy(&listing.stderr)
        ));
    }

    let mut long = Vec::new();
    for path in listing.stdout.split(|&byte| byte == 0) {
        let path = String::from_utf8_lossy(path);
        if path.is_empty() || !is_checked(&path) {
            continue;
        }
        // A file git tracks but the checkout lacks (deleted, not staged) has no lines.
        let Ok(text) = std::fs::read(root.join(path.as_ref())) else {
            continue;
        };
        let lines = line_count(&text);
        if lines > MAX_LINES {
            long.push((lines, path.into_owned()));
        }
    }

    if long.is_empty() {
        return Ok(0);
    }
    long.sort_by(|a, b| b.cmp(a));
    eprintln!(
        "{} files of code are longer than {MAX_LINES} lines (AGENTS.md, \"Files of at most 500 \
         lines\"):",
        long.len()
    );
    for (lines, path) in &long {
        eprintln!("{lines:>6} {path}");
    }
    Ok(1)
}
